version: 0.2
# env:
  # variables:
    # WEBSITE_BUCKET_URL= "s3://static-website-bucket-test-abc-1/"
    # STATIC_WEBSITE_ROOT= "/project2-static-website/website"
phases:
  pre_build:
    commands:
      - echo "we are runing pre build staff"
  build:
    commands:
      - echo "env var static_website root"
      - echo $STATIC_WEBSITE_ROOT
      - echo "env var website bucket url"
      - echo $WEBSITE_BUCKET_URL
      - aws s3 cp ./project2-static-website/website s3://static-website-bucket-test-abc-1/  --recursive
